### ISSUE TITLE
How to build kernel for other devices?

### ISSUE THREAD

**Issue by QueueRear** [interactionlab/InfiniTouch#1]
I've read the instruction of [ACCESSING RAW CAPACITIVE IMAGES ON COMMODITY SMARTPHONES](http://huyle.de/blog/capacitive-images/), where it's mentioned that a modified kernel is required but compiling a whole Android kernel is time-comsuming thus a compiled kernel is provided in this repository.

The tutorial is quite helpful, but I wonder how to apply it to other Android devices equipped with Synaptics touchscreens. I can find a proper modified kernel, but how can I only compile the needed part of the kernel instead of an entire one to a flashable zip file?

I'll be greatly grateful if you can give me any help.

**Comment by sven-mayer** [comment]
@QueueRear, the kernel must be compiled per device as they are device and even Android version specific. Thus, you need to build the whole OS to get the kernel needed for your specific device.

If you have a kernel, you can copy the kernel in via "adb shell" no need to flash the whole Android via ZIP file; however, you need to acquire root rights first.

**Comment by QueueRear** [comment]
Thx for your detailed reply greatly! It helps a lot and I've modified my device successfully.
